[project]
name = "mobile-manipulator"
version = "0.1.0"
description = "Mujoco Simulation Project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mujoco==3.10.0",
    "numpy==2.2.6",
    "glfw==2.10.0",
    "pyopengl==3.1.10",
    "absl-py==2.4.0",
    "etils==1.13.0",
    "fsspec==2026.6.0",
    "typing-extensions==4.15.0",
    "importlib-resources==7.1.0",
    "zipp==4.1.0",
    "loop-rate-limiters>=1.2.0",
    "mink>=1.2.0",
    "babyros",
]

[tool.uv.workspace]
members = [
    "lib/babyros",
]

[tool.uv.sources]
babyros = { workspace = true }
