from planning.trajectory_planner import TrajectoryPlanner, PlannedTrajectory
from planning.trajectory_optimizer import TrajectoryOptimizer, HeadingTracker
from planning.task_definitions import build_pick_and_place_sequence